// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2MD0LUcW-9nPqdFhN9Zqj3YQw1sYXuXM',
    appId: '1:167655419936:web:cfd81e6744cbbd4b28cc45',
    messagingSenderId: '167655419936',
    projectId: 'greenquest-f2f16',
    authDomain: 'greenquest-f2f16.firebaseapp.com',
    storageBucket: 'greenquest-f2f16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbAOL8l8snYsd7SLuF1mJQGRRZ0npwNGM',
    appId: '1:167655419936:android:7e6992acd60c655228cc45',
    messagingSenderId: '167655419936',
    projectId: 'greenquest-f2f16',
    storageBucket: 'greenquest-f2f16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVgV839DFj7Knp3Iacvyi5_THDaRUMxo0',
    appId: '1:167655419936:ios:212b10681da4e98728cc45',
    messagingSenderId: '167655419936',
    projectId: 'greenquest-f2f16',
    storageBucket: 'greenquest-f2f16.appspot.com',
    iosBundleId: 'com.example.greenQuest',
  );
}
